import { Demanda, User, Resposta, Categoria, TipoBarreira } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Ana Paula Souza',
    email: 'ana.souza@petrobras.com.br',
    role: 'USER',
    department: 'RH',
    unit: 'Sede Rio de Janeiro',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Carlos Eduardo Lima',
    email: 'carlos.lima@petrobras.com.br',
    role: 'USER',
    department: 'TI',
    unit: 'Refinaria REPLAN',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '3',
    name: 'Mariana Costa',
    email: 'mariana.costa@petrobras.com.br',
    role: 'ADMIN',
    department: 'Sustentabilidade e Acessibilidade',
    unit: 'Sede Rio de Janeiro',
    createdAt: new Date('2023-11-01'),
    updatedAt: new Date('2023-11-01'),
  },
  {
    id: '4',
    name: 'Pedro Alves',
    email: 'pedro.alves@petrobras.com.br',
    role: 'USER',
    department: 'Operações',
    unit: 'E&P Bacia de Campos',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
];

export const mockCategorias: Categoria[] = [
  { id: '1', nome: 'Acessibilidade',     cor: '#009B3A', icone: 'accessibility' },
  { id: '2', nome: 'Inclusão',           cor: '#FEDF00', icone: 'users' },
  { id: '3', nome: 'Processos Internos', cor: '#2563EB', icone: 'settings' },
  { id: '4', nome: 'Comunicação',        cor: '#9333EA', icone: 'message-circle' },
  { id: '5', nome: 'Tecnologia',         cor: '#D97706', icone: 'cpu' },
  { id: '6', nome: 'Infraestrutura',     cor: '#DC2626', icone: 'building' },
];

export const mockBarreiras: TipoBarreira[] = [
  { id: '1', slug: 'arquitetonica',  nome: 'Arquitetônica',  descricao: 'Barreiras físicas no ambiente' },
  { id: '2', slug: 'comunicacional', nome: 'Comunicacional', descricao: 'Dificuldades de comunicação' },
  { id: '3', slug: 'tecnologica',    nome: 'Tecnológica',    descricao: 'Problemas com sistemas e ferramentas' },
  { id: '4', slug: 'transporte',     nome: 'Transporte',     descricao: 'Dificuldades de locomoção' },
  { id: '5', slug: 'institucional',  nome: 'Institucional',  descricao: 'Barreiras em normas e processos' },
  { id: '6', slug: 'atitudinal',     nome: 'Atitudinal',     descricao: 'Comportamentos e atitudes' },
  { id: '7', slug: 'cultural',       nome: 'Cultural',       descricao: 'Questões culturais e de diversidade' },
];

export const mockRespostas: Resposta[] = [
  {
    id: 'r1',
    conteudo: 'Obrigada por registrar esta demanda. Já encaminhamos para a equipe de infraestrutura verificar a rampa de acesso na entrada principal. Daremos retorno em até 5 dias úteis.',
    autor: mockUsers[2],
    isAdminResponse: true,
    demandaId: '1',
    createdAt: new Date('2024-04-02'),
    updatedAt: new Date('2024-04-02'),
  },
  {
    id: 'r2',
    conteudo: 'Boa tarde! Complementando meu relato: a rampa fica na lateral do prédio B, próxima ao estacionamento. No período de chuva fica escorregadia e sem corrimão.',
    autor: mockUsers[0],
    isAdminResponse: false,
    demandaId: '1',
    createdAt: new Date('2024-04-03'),
    updatedAt: new Date('2024-04-03'),
  },
];

export const mockDemandas: Demanda[] = [
  {
    id: '1',
    titulo: 'Rampa de acesso sem corrimão no Prédio B',
    descricao:
      'A rampa de acesso para cadeirantes no Prédio B está sem corrimão e apresenta superfície escorregadia em dias de chuva, representando risco de acidentes. Solicito manutenção urgente e instalação de corrimão bilateral conforme normas ABNT.',
    status: 'EM_ANDAMENTO',
    prioridade: 'ALTA',
    categoria: mockCategorias[0],
    tipoBarreira: mockBarreiras[0],
    unidade: 'Sede Rio de Janeiro',
    autor: mockUsers[0],
    respostas: mockRespostas,
    tags: ['rampa', 'corrimão', 'ABNT'],
    visualizacoes: 47,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-03'),
  },
  {
    id: '2',
    titulo: 'Sistema de ponto digital inacessível para deficientes visuais',
    descricao:
      'O novo sistema de ponto eletrônico não possui suporte a leitores de tela. Colaboradores com deficiência visual não conseguem registrar o ponto de forma autônoma e precisam pedir ajuda a colegas.',
    status: 'EM_ANALISE',
    prioridade: 'URGENTE',
    categoria: mockCategorias[4],
    tipoBarreira: mockBarreiras[2],
    unidade: 'Refinaria REPLAN',
    autor: mockUsers[1],
    respostas: [],
    tags: ['leitor de tela', 'ponto eletrônico', 'WCAG'],
    visualizacoes: 83,
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
  },
  {
    id: '3',
    titulo: 'Falta de intérprete de Libras nas reuniões gerenciais',
    descricao:
      'Colaboradores surdos não têm acesso a intérprete de Libras durante reuniões gerenciais e treinamentos obrigatórios. Isso compromete a participação plena e o desenvolvimento profissional.',
    status: 'NOVA',
    prioridade: 'ALTA',
    categoria: mockCategorias[1],
    tipoBarreira: mockBarreiras[1],
    unidade: 'Sede Rio de Janeiro',
    autor: mockUsers[3],
    respostas: [],
    tags: ['libras', 'inclusão', 'treinamento'],
    visualizacoes: 29,
    createdAt: new Date('2024-04-08'),
    updatedAt: new Date('2024-04-08'),
  },
  {
    id: '4',
    titulo: 'Documentos internos sem versão acessível (sem Alt Text)',
    descricao:
      'Os PDFs e apresentações enviados pela comunicação interna não possuem texto alternativo nas imagens nem estrutura de cabeçalhos adequada, impossibilitando leitura por tecnologias assistivas.',
    status: 'RESPONDIDA',
    prioridade: 'MEDIA',
    categoria: mockCategorias[3],
    tipoBarreira: mockBarreiras[1],
    unidade: 'E&P Bacia de Campos',
    autor: mockUsers[3],
    respostas: [],
    tags: ['PDF', 'alt text', 'comunicação interna'],
    visualizacoes: 15,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-03-28'),
  },
  {
    id: '5',
    titulo: 'Banheiro adaptado do 3º andar interditado há 3 meses',
    descricao:
      'O único banheiro adaptado do 3º andar está em obras há mais de 3 meses sem previsão de conclusão. Colaboradores com mobilidade reduzida precisam se deslocar até o térreo, o que causa transtornos diários.',
    status: 'RESOLVIDA',
    prioridade: 'ALTA',
    categoria: mockCategorias[0],
    tipoBarreira: mockBarreiras[0],
    unidade: 'Sede Rio de Janeiro',
    autor: mockUsers[0],
    respostas: [],
    tags: ['banheiro adaptado', 'obras', 'mobilidade'],
    visualizacoes: 62,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-03-15'),
  },
];
