import { Demanda, User, Resposta } from '@/types';
import { DemandaStatus, TipoBarreira } from '@/lib/constants';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Ana Paula Souza',
    email: 'ana.souza@petrobras.com.br',
    role: 'USER',
    department: 'Recursos Humanos',
    unit: 'Sede Rio de Janeiro (EDISE)',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Carlos Eduardo Lima',
    email: 'carlos.lima@petrobras.com.br',
    role: 'USER',
    department: 'Tecnologia da Informação',
    unit: 'Refinaria REPLAN',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '3',
    name: 'Mariana Costa',
    email: 'mariana.costa@petrobras.com.br',
    role: 'ADMIN',
    department: 'Sustentabilidade e Acessibilidade',
    unit: 'Sede Rio de Janeiro (EDISE)',
    createdAt: new Date('2023-11-01'),
    updatedAt: new Date('2023-11-01'),
  },
];

export const mockRespostas: Resposta[] = [
  {
    id: 'r1',
    conteudo: 'Prezada Ana, seu relato foi recebido pela Gerência de Infraestrutura. Uma equipe técnica foi enviada ao local para realizar o nivelamento da rampa e instalar o corrimão conforme as normas de acessibilidade (ABNT NBR 9050).',
    autor: mockUsers[2],
    isAdminResponse: true,
    demandaId: '1',
    createdAt: new Date('2024-04-02'),
    updatedAt: new Date('2024-04-02'),
  },
];

export const mockDemandas: Demanda[] = [
  {
    id: '1',
    titulo: 'Rampa de acesso ao Prédio B sem corrimão',
    descricao: 'A rampa de acesso principal ao Bloco B está sem corrimão bilateral, dificultando a locomoção de colaboradores com mobilidade reduzida e violando normas técnicas de segurança e acessibilidade.',
    status: DemandaStatus.EM_ANDAMENTO,
    prioridade: 'ALTA',
    categoria: { id: 'c1', nome: 'Infraestrutura' },
    tipoBarreira: { id: 'b1', slug: TipoBarreira.ARQUITETONICA, nome: 'Arquitetônica' },
    unidade: 'EDISE - Rio de Janeiro',
    autor: mockUsers[0],
    respostas: mockRespostas,
    votos: 12,
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2024-04-03T14:30:00Z',
  },
  {
    id: '2',
    titulo: 'Ponto Eletrônico Inacessível para Baixa Visão',
    descricao: 'O software de registro de jornada não possui contraste adequado nem compatibilidade com leitores de tela como NVDA/JAWS, impedindo o registro autônomo por pessoas com deficiência visual.',
    status: DemandaStatus.EM_ANALISE,
    prioridade: 'URGENTE',
    categoria: { id: 'c2', nome: 'Digital' },
    tipoBarreira: { id: 'b2', slug: TipoBarreira.TECNOLOGICA, nome: 'Tecnológica' },
    unidade: 'Refinaria REPLAN',
    autor: mockUsers[1],
    respostas: [],
    votos: 28,
    createdAt: '2024-04-05T08:15:00Z',
    updatedAt: '2024-04-05T08:15:00Z',
  },
  {
    id: '3',
    titulo: 'Ausência de Intérprete de Libras em Treinamentos',
    descricao: 'Os treinamentos de segurança (SMS) realizados presencialmente na unidade não contam com suporte de intérprete de Libras, excluindo colaboradores surdos de informações críticas.',
    status: DemandaStatus.NOVA,
    prioridade: 'ALTA',
    categoria: { id: 'c3', nome: 'Comunicação' },
    tipoBarreira: { id: 'b3', slug: TipoBarreira.COMUNICACIONAL, nome: 'Comunicacional' },
    unidade: 'EDISE - Rio de Janeiro',
    autor: mockUsers[2],
    respostas: [],
    votos: 5,
    createdAt: '2024-04-10T09:00:00Z',
    updatedAt: '2024-04-10T09:00:00Z',
  },
  {
    id: '4',
    titulo: 'Banheiro Adaptado Interditado no 4º Andar',
    descricao: 'O único sanitário acessível do pavimento está em manutenção há mais de 15 dias sem equipe trabalhando no local, obrigando deslocamentos longos para outros andares.',
    status: DemandaStatus.RESOLVIDA,
    prioridade: 'MEDIA',
    categoria: { id: 'c1', nome: 'Infraestrutura' },
    tipoBarreira: { id: 'b1', slug: TipoBarreira.ARQUITETONICA, nome: 'Arquitetônica' },
    unidade: 'EDISE - Rio de Janeiro',
    autor: mockUsers[0],
    respostas: [],
    votos: 3,
    createdAt: '2024-03-15T11:00:00Z',
    updatedAt: '2024-03-25T16:00:00Z',
  }
];

